### PR TITLE
Fully resolves the path to /etc/localtime on the host.

### LINKED ISSUE #145: relative symlink for /etc/localtime causes run to fail
host machine: `readlink /etc/localtime -> ../usr/share/zoneinfo/Etc/UTC`

setup:

```
acbuild begin
acbuild dependency add s3.amazonaws.com/bsd-aci/base/centos7 --label version=4b6264c-14
acbuild mount add resolvconf /etc/resolv.conf --read-only
acbuild set-name whatev
acbuild set-exec /bin/bash
acbuild run /bin/true
```

If I run this in `/tmp` it works.  If I run in `/tmp/foo` it fails because `acbuild` resolves the symlink relative to the current directory, rather than to `/etc`:
```
run: open ../usr/share/zoneinfo/Etc/UTC: no such file or directory
```

### PR DESCRIPTION
**Pull request by blalor**
Fixes #145.  Also affects #142: `usr` is no longer a child of `rootfs` and `manifest` in `.acbuild/currentaci`.

### CODE REVIEW

**Comment by dgonyeo** [comment]
Related: https://github.com/appc/acbuild/pull/134. I'd be fine with rebasing that on top of this.

**Comment by dgonyeo** [comment]
LGTM, cc @jonboulle

**Comment by blalor** [comment]
#134 may actually be obsoleted by this. [`EvalSymlinks`](https://golang.org/pkg/path/filepath/#EvalSymlinks):

> EvalSymlinks returns the path name after the evaluation of any symbolic links. If path is relative the result will be relative to the current directory, unless one of the components is an absolute symbolic link.

File: lib/run.go [hunk 1]
```diff
@@ -266,7 +266,7 @@ func genDeplist(acipath string, reg registry.Registry) ([]string, error) {
 }
 
 func (a *ACBuild) mirrorLocalZoneInfo() error {
-	zif, err := os.Readlink("/etc/localtime")
+	zif, err := filepath.EvalSymlinks("/etc/localtime")
```
Comment (jonboulle) [inline lib/run.go]: Is this preferable to the rkt approach for some reason? https://github.com/coreos/rkt/blob/master/stage1/init/init.go#L106-L110
if so we should probably switch there too

**Comment by jonboulle** [comment]
yeah per https://github.com/appc/acbuild/pull/134#issuecomment-160739791 I think I'd rather axe that and just go with this fix.

File: lib/run.go (hunk 1 above)
Comment (jonboulle) [inline lib/run.go]: @dgonyeo ?
